### ISSUE TITLE
[Question] How do i solve this captcha?

### ISSUE THREAD

**Issue by zeroq9** [J-Rios/multicolor-captcha-generator#12]
Sorry if this is a stupid question but i came across these captchas on the internet and i just cant solve them, came across this github and thought you guys might be able to help

my initial answer would be: 3Qt4m4u3

![get-captcha-image](https://github.com/J-Rios/multicolorcaptcha/assets/60327999/db94c73d-2e7e-47d1-bd8f-244d5282d4e6)

**Comment by J-Rios** [comment]
Hi, current library from this Github doesn't add that small letters/numbers in the image, just 4 big characters, so could be from someone that fork this library and modify It to add that extra thing...

So I'm not sure, but I bet you should just care of the Big letters/characters and ignore the smaller ones. In this case:

Q443

Best Regards :)
