### ISSUE TITLE
[Question] How to remove the dark background?

### ISSUE THREAD

**Issue by Qmlio** [J-Rios/multicolor-captcha-generator#14]
Greetings, 
How can i remove the black background from the generated images, i know there are many options out there for cropping but i want to know if its possible to remove it before i resort to other options.
![a](https://github.com/J-Rios/multicolorcaptcha/assets/65741732/69fb4948-c0dc-44c2-9b80-9ff16fe161d6)

**Comment by J-Rios** [comment]
Hello, you mean the black upper and bottom margings?

There is a "margin" argument in the "gen_captcha_image" function that you can set to False to avoid this black margins appear in the image:

```python
captcha = CaptchaGen.gen_captcha_image(multicolor=True, margin=False)
```

Regards

**Comment by Qmlio** [comment]
Oh.ok..thanks for the response and clarification
